services:
  app:
    build:
      context: .
      target: ${TARGET_STAGE:-development}
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:8080
    volumes:
      - ./:/src
