package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/tea-party-developers/ramen-graphql/internal/graphql/model"
)

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context) (*model.Post, error) {
	caption := "おいしいラーメン！"
	userImage := "https://via.placeholder.com/150"
	return &model.Post{
		ID:      "1",
		Image:   "https://via.placeholder.com/600",
		Caption: &caption,
		PostedBy: &model.User{
			ID:    "1",
			Name:  "john_doe",
			Image: &userImage,
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
